### ISSUE TITLE
Where to find the dataset?

### ISSUE THREAD

**Issue by IbtihajT** [Ign0reLee/DeepBall_Tensorflow#1]
Kindly provide the links to where I can get the dataset. 

I tried to download the ISSIA-CNR Soccer Dataset (D’Orazio et al., 2009) from the link https://fox.ino.it/home/spagnolo/Dataset.html but it's a 404. Please help.

**Comment by Ign0reLee** [comment]
Dear lbtihajT

Hi, and sorry for replying so late.

Unfortunately, the link can no longer be found. Even if you suggest another link, the data is no longer available.

Therefore, I used the basketball dataset, and I wrote the code using my own dataset.

However, the project is no longer supported and has been discontinued, so I can not upload it

I wish you good luck.
